export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
